### ISSUE TITLE
Question: duplicated code

### ISSUE THREAD

**Issue by misiek08** [NicolasLM/nucleon#7]
Hello!
I'm new to Rust and this example (load balancer) is very interesting for me.

Can you tell me if I'm correct:
https://github.com/NicolasLM/nucleon/blob/master/src/tcplb.rs#L92
and
https://github.com/NicolasLM/nucleon/blob/master/src/tcplb.rs#L607
are duplicating registering interest about writeable?

So [this register](https://github.com/NicolasLM/nucleon/blob/master/src/tcplb.rs#L92) or [this register](https://github.com/NicolasLM/nucleon/blob/master/src/tcplb.rs#L607) can be removed?

**Comment by NicolasLM** [comment]
Hi,
A quick look at it seems to indicate that you are right. However this code is not so fresh in my mind anymore so I may be missing something.

As you probably noticed this code was last updated a year and a half ago. So many things happened in the meantime in the Rust language that this code is probably not idiomatic Rust anymore. Please keep that in mind while studying this code :)
